class Kana {
  String char;
  String latin;
  Kana({this.char, this.latin});
}

List<Kana> kanaList = [
  Kana(char: 'あ', latin: 'a'),
  Kana(char: 'い', latin: 'i'),
  Kana(char: 'う', latin: 'u'),
  Kana(char: 'え', latin: 'e'),
  Kana(char: 'お', latin: 'o'),
  Kana(char: 'か', latin: 'ka'),
  Kana(char: 'き', latin: 'ki'),
  Kana(char: 'く', latin: 'ku'),
  Kana(char: 'け', latin: 'ke'),
  Kana(char: 'こ', latin: 'ko'),
  Kana(char: 'さ', latin: 'sa'),
  Kana(char: 'し', latin: 'shi'),
  Kana(char: 'す', latin: 'su'),
  Kana(char: 'せ', latin: 'se'),
  Kana(char: 'そ', latin: 'so'),
  Kana(char: 'た', latin: 'ta'),
  Kana(char: 'ち', latin: 'chi'),
  Kana(char: 'つ', latin: 'tsu'),
  Kana(char: 'て', latin: 'te'),
  Kana(char: 'と', latin: 'to'),
  Kana(char: 'な', latin: 'na'),
  Kana(char: 'に', latin: 'ni'),
  Kana(char: 'ぬ', latin: 'nu'),
  Kana(char: 'ね', latin: 'ne'),
  Kana(char: 'の', latin: 'no'),
  Kana(char: 'は', latin: 'ha'),
  Kana(char: 'ひ', latin: 'hi'),
  Kana(char: 'ふ', latin: 'hu'),
  Kana(char: 'へ', latin: 'he'),
  Kana(char: 'ほ', latin: 'ho'),
  Kana(char: 'ま', latin: 'ma'),
  Kana(char: 'み', latin: 'mi'),
  Kana(char: 'む', latin: 'mu'),
  Kana(char: 'め', latin: 'me'),
  Kana(char: 'も', latin: 'mo'),
  Kana(char: 'ら', latin: 'ra'),
  Kana(char: 'り', latin: 'ri'),
  Kana(char: 'る', latin: 'ru'),
  Kana(char: 'れ', latin: 're'),
  Kana(char: 'ろ', latin: 'ro'),
  Kana(char: 'や', latin: 'ya'),
  Kana(char: 'ゆ', latin: 'yu'),
  Kana(char: 'よ', latin: 'yo'),
  Kana(char: 'わ', latin: 'wa'),
  Kana(char: 'を', latin: 'wo'),
  Kana(char: 'ん', latin: 'n'),
];

List<Kana> kanaList2 = [
  Kana(char: 'が', latin: 'ga'),
  Kana(char: 'ぎ', latin: 'gi'),
  Kana(char: 'ぐ', latin: 'gu'),
  Kana(char: 'げ', latin: 'ge'),
  Kana(char: 'ご', latin: 'go'),
  Kana(char: 'ざ', latin: 'za'),
  Kana(char: 'じ', latin: 'ji'),
  Kana(char: 'ず', latin: 'zu'),
  Kana(char: 'ぜ', latin: 'ze'),
  Kana(char: 'ぞ', latin: 'zo'),
  Kana(char: 'だ', latin: 'da'),
  Kana(char: 'ぢ', latin: 'ji'),
  Kana(char: 'づ', latin: 'dzu'),
  Kana(char: 'で', latin: 'de'),
  Kana(char: 'ど', latin: 'do'),
  Kana(char: 'ば', latin: 'ba'),
  Kana(char: 'び', latin: 'bi'),
  Kana(char: 'ぶ', latin: 'bu'),
  Kana(char: 'べ', latin: 'be'),
  Kana(char: 'ぼ', latin: 'bo'),
  Kana(char: 'ぱ', latin: 'pa'),
  Kana(char: 'ぴ', latin: 'pi'),
  Kana(char: 'ぷ', latin: 'pu'),
  Kana(char: 'ぺ', latin: 'pe'),
  Kana(char: 'ぽ', latin: 'po'),
];

List<Kana> KatakanaList = [
  Kana(char: 'ア', latin: 'a'),
  Kana(char: 'イ', latin: 'i'),
  Kana(char: 'ウ', latin: 'u'),
  Kana(char: 'エ', latin: 'e'),
  Kana(char: 'オ', latin: 'o'),
  Kana(char: 'カ', latin: 'ka'),
  Kana(char: 'キ', latin: 'ki'),
  Kana(char: 'ク', latin: 'ku'),
  Kana(char: 'ケ', latin: 'ke'),
  Kana(char: 'コ', latin: 'ko'),
  Kana(char: 'サ', latin: 'sa'),
  Kana(char: 'シ', latin: 'shi'),
  Kana(char: 'ス', latin: 'su'),
  Kana(char: 'セ', latin: 'se'),
  Kana(char: 'ソ', latin: 'so'),
  Kana(char: 'タ', latin: 'ta'),
  Kana(char: 'チ', latin: 'chi'),
  Kana(char: 'ツ', latin: 'tsu'),
  Kana(char: 'テ', latin: 'te'),
  Kana(char: 'ト', latin: 'to'),
  Kana(char: 'ナ', latin: 'na'),
  Kana(char: '二', latin: 'ni'),
  Kana(char: 'ヌ', latin: 'nu'),
  Kana(char: 'ネ', latin: 'ne'),
  Kana(char: 'ノ', latin: 'no'),
  Kana(char: 'ハ', latin: 'ha'),
  Kana(char: 'ヒ', latin: 'hi'),
  Kana(char: 'フ', latin: 'hu'),
  Kana(char: 'へ', latin: 'he'),
  Kana(char: 'ホ', latin: 'ho'),
  Kana(char: 'マ', latin: 'ma'),
  Kana(char: '三', latin: 'mi'),
  Kana(char: 'ム', latin: 'mu'),
  Kana(char: 'メ', latin: 'me'),
  Kana(char: 'モ', latin: 'mo'),
  Kana(char: 'ラ', latin: 'ra'),
  Kana(char: 'リ', latin: 'ri'),
  Kana(char: 'ル', latin: 'ru'),
  Kana(char: 'レ', latin: 're'),
  Kana(char: 'ロ', latin: 'ro'),
  Kana(char: 'ヤ', latin: 'ya'),
  Kana(char: 'ユ', latin: 'yu'),
  Kana(char: 'ヨ', latin: 'yo'),
  Kana(char: 'ワ', latin: 'wa'),
  Kana(char: 'ヲ', latin: 'wo'),
  Kana(char: 'ン', latin: 'n'),
];

List<Kana> numbersList = [
  Kana(char: '一', latin: '１　「いち」'),
  Kana(char: '二', latin: '２　「に」'),
  Kana(char: '三', latin: '３　「さん」'),
  Kana(char: '四', latin: '４　「し」'),
  Kana(char: '五', latin: '５　「ご」'),
  Kana(char: '六', latin: '６　「ろく」'),
  Kana(char: '七', latin: '７　「なな」'),
  Kana(char: '八', latin: '８　「はち」'),
  Kana(char: '九', latin: '９　「きゅう」'),
  Kana(char: '十', latin: '１０　「じゅう」'),
];
