List grade1Kanjis = [
  {
    "kanji": "一",
    "grade": 1,
    "stroke_count": 1,
    "meanings": ["one", "one radical (no.1)"],
    "kun_readings": ["ひと-", "ひと.つ"],
    "on_readings": ["イチ", "イツ"],
    "name_readings": [
      "かず",
      "い",
      "いっ",
      "いる",
      "かつ",
      "かづ",
      "てん",
      "はじめ",
      "ひ",
      "ひとつ",
      "まこと"
    ],
    "jlpt": 4,
    "unicode": "4e00",
    "heisig_en": "one"
  },
  {
    "kanji": "右",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["right"],
    "kun_readings": ["みぎ"],
    "on_readings": ["ウ", "ユウ"],
    "name_readings": ["あき", "すけ"],
    "jlpt": 4,
    "unicode": "53f3",
    "heisig_en": "right"
  },
  {
    "kanji": "雨",
    "grade": 1,
    "stroke_count": 8,
    "meanings": ["rain"],
    "kun_readings": ["あめ", "あま-", "-さめ"],
    "on_readings": ["ウ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "96e8",
    "heisig_en": "rain"
  },
  {
    "kanji": "円",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["circle", "yen", "round"],
    "kun_readings": ["まる.い", "まる", "まど", "まど.か", "まろ.やか"],
    "on_readings": ["エン"],
    "name_readings": ["つぶら", "のぶ", "まどか", "みつ"],
    "jlpt": 4,
    "unicode": "5186",
    "heisig_en": "circle"
  },
  {
    "kanji": "王",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["king", "rule", "magnate"],
    "kun_readings": [],
    "on_readings": ["オウ", "-ノウ"],
    "name_readings": ["おお", "おおきみ", "わ"],
    "jlpt": 2,
    "unicode": "738b",
    "heisig_en": "king"
  },
  {
    "kanji": "音",
    "grade": 1,
    "stroke_count": 9,
    "meanings": ["sound", "noise"],
    "kun_readings": ["おと", "ね"],
    "on_readings": ["オン", "イン", "-ノン"],
    "name_readings": ["お", "と"],
    "jlpt": 3,
    "unicode": "97f3",
    "heisig_en": "sound"
  },
  {
    "kanji": "下",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["below", "down", "descend", "give", "low", "inferior"],
    "kun_readings": [
      "した",
      "しも",
      "もと",
      "さ.げる",
      "さ.がる",
      "くだ.る",
      "くだ.り",
      "くだ.す",
      "-くだ.す",
      "くだ.さる",
      "お.ろす",
      "お.りる"
    ],
    "on_readings": ["カ", "ゲ"],
    "name_readings": ["さか", "しと"],
    "jlpt": 4,
    "unicode": "4e0b",
    "heisig_en": "below"
  },
  {
    "kanji": "火",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["fire"],
    "kun_readings": ["ひ", "-び", "ほ-"],
    "on_readings": ["カ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "706b",
    "heisig_en": "fire"
  },
  {
    "kanji": "花",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["flower"],
    "kun_readings": ["はな"],
    "on_readings": ["カ", "ケ"],
    "name_readings": ["わ"],
    "jlpt": 4,
    "unicode": "82b1",
    "heisig_en": "flower"
  },
  {
    "kanji": "貝",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["shellfish"],
    "kun_readings": ["かい"],
    "on_readings": ["バイ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "8c9d",
    "heisig_en": "shellfish"
  },
  {
    "kanji": "学",
    "grade": 1,
    "stroke_count": 8,
    "meanings": ["study", "learning", "science"],
    "kun_readings": ["まな.ぶ"],
    "on_readings": ["ガク"],
    "name_readings": ["たか", "のり"],
    "jlpt": 4,
    "unicode": "5b66",
    "heisig_en": "study"
  },
  {
    "kanji": "気",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["spirit", "mind", "air", "atmosphere", "mood"],
    "kun_readings": ["いき"],
    "on_readings": ["キ", "ケ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "6c17",
    "heisig_en": "spirit"
  },
  {
    "kanji": "休",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["rest", "day off", "retire", "sleep"],
    "kun_readings": ["やす.む", "やす.まる", "やす.める"],
    "on_readings": ["キュウ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "4f11",
    "heisig_en": "rest"
  },
  {
    "kanji": "玉",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["jewel", "ball"],
    "kun_readings": ["たま", "たま-", "-だま"],
    "on_readings": ["ギョク"],
    "name_readings": ["おう", "だん"],
    "jlpt": 2,
    "unicode": "7389",
    "heisig_en": "jewel"
  },
  {
    "kanji": "金",
    "grade": 1,
    "stroke_count": 8,
    "meanings": ["gold"],
    "kun_readings": ["かね", "かな-", "-がね"],
    "on_readings": ["キン", "コン", "ゴン"],
    "name_readings": ["かん", "きむ", "こ", "この", "ん"],
    "jlpt": 4,
    "unicode": "91d1",
    "heisig_en": "gold"
  },
  {
    "kanji": "九",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["nine"],
    "kun_readings": ["ここの", "ここの.つ"],
    "on_readings": ["キュウ", "ク"],
    "name_readings": ["いちじく", "いちのく", "この", "ひさし"],
    "jlpt": 4,
    "unicode": "4e5d",
    "heisig_en": "nine"
  },
  {
    "kanji": "空",
    "grade": 1,
    "stroke_count": 8,
    "meanings": ["empty", "sky", "void", "vacant", "vacuum"],
    "kun_readings": ["そら", "あ.く", "あ.き", "あ.ける", "から", "す.く", "す.かす", "むな.しい"],
    "on_readings": ["クウ"],
    "name_readings": ["うつ", "き", "く"],
    "jlpt": 4,
    "unicode": "7a7a",
    "heisig_en": "empty"
  },
  {
    "kanji": "月",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["month", "moon"],
    "kun_readings": ["つき"],
    "on_readings": ["ゲツ", "ガツ"],
    "name_readings": ["おと", "がっ", "す", "ずき", "もり"],
    "jlpt": 4,
    "unicode": "6708",
    "heisig_en": "month"
  },
  {
    "kanji": "犬",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["dog"],
    "kun_readings": ["いぬ", "いぬ-"],
    "on_readings": ["ケン"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "72ac",
    "heisig_en": "dog"
  },
  {
    "kanji": "見",
    "grade": 1,
    "stroke_count": 7,
    "meanings": [
      "see",
      "hopes",
      "chances",
      "idea",
      "opinion",
      "look at",
      "visible"
    ],
    "kun_readings": ["み.る", "み.える", "み.せる"],
    "on_readings": ["ケン"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "898b",
    "heisig_en": "see"
  },
  {
    "kanji": "五",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["five"],
    "kun_readings": ["いつ", "いつ.つ"],
    "on_readings": ["ゴ"],
    "name_readings": ["い", "さ", "さつ", "ち", "ふ", "み", "め"],
    "jlpt": 4,
    "unicode": "4e94",
    "heisig_en": "five"
  },
  {
    "kanji": "口",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["mouth"],
    "kun_readings": ["くち"],
    "on_readings": ["コウ", "ク"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "53e3",
    "heisig_en": "mouth"
  },
  {
    "kanji": "校",
    "grade": 1,
    "stroke_count": 10,
    "meanings": ["exam", "school", "printing", "proof", "correction"],
    "kun_readings": [],
    "on_readings": ["コウ", "キョウ"],
    "name_readings": ["めん"],
    "jlpt": 4,
    "unicode": "6821",
    "heisig_en": "exam"
  },
  {
    "kanji": "左",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["left"],
    "kun_readings": ["ひだり"],
    "on_readings": ["サ", "シャ"],
    "name_readings": ["そ"],
    "jlpt": 4,
    "unicode": "5de6",
    "heisig_en": "left"
  },
  {
    "kanji": "三",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["three"],
    "kun_readings": ["み", "み.つ", "みっ.つ"],
    "on_readings": ["サン", "ゾウ"],
    "name_readings": [
      "か",
      "さ",
      "さい",
      "さえ",
      "さぶ",
      "ざ",
      "ざえ",
      "ざぶ",
      "そう",
      "ぞ",
      "ただ",
      "みつ",
      "みん",
      "も",
      "や"
    ],
    "jlpt": 4,
    "unicode": "4e09",
    "heisig_en": "three"
  },
  {
    "kanji": "山",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["mountain"],
    "kun_readings": ["やま"],
    "on_readings": ["サン", "セン"],
    "name_readings": ["さ", "やの", "やん"],
    "jlpt": 4,
    "unicode": "5c71",
    "heisig_en": "mountain"
  },
  {
    "kanji": "四",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["four"],
    "kun_readings": ["よ", "よ.つ", "よっ.つ", "よん"],
    "on_readings": ["シ"],
    "name_readings": ["あ", "つ", "よつ"],
    "jlpt": 4,
    "unicode": "56db",
    "heisig_en": "four"
  },
  {
    "kanji": "子",
    "grade": 1,
    "stroke_count": 3,
    "meanings": [
      "child",
      "sign of the rat",
      "11PM-1AM",
      "first sign of Chinese zodiac"
    ],
    "kun_readings": ["こ", "-こ", "ね"],
    "on_readings": ["シ", "ス", "ツ"],
    "name_readings": ["い", "き", "ぎ", "く", "け", "ねっ"],
    "jlpt": 4,
    "unicode": "5b50",
    "heisig_en": "child"
  },
  {
    "kanji": "糸",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["thread"],
    "kun_readings": ["いと"],
    "on_readings": ["シ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "7cf8",
    "heisig_en": "thread"
  },
  {
    "kanji": "字",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["character", "letter", "word", "section of village"],
    "kun_readings": ["あざ", "あざな", "-な"],
    "on_readings": ["ジ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5b57",
    "heisig_en": "character"
  },
  {
    "kanji": "耳",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["ear"],
    "kun_readings": ["みみ"],
    "on_readings": ["ジ"],
    "name_readings": ["がみ"],
    "jlpt": 4,
    "unicode": "8033",
    "heisig_en": "ear"
  },
  {
    "kanji": "七",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["seven"],
    "kun_readings": ["なな", "なな.つ", "なの"],
    "on_readings": ["シチ"],
    "name_readings": ["し", "しっ", "な", "ひち"],
    "jlpt": 4,
    "unicode": "4e03",
    "heisig_en": "seven"
  },
  {
    "kanji": "車",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["car"],
    "kun_readings": ["くるま"],
    "on_readings": ["シャ"],
    "name_readings": ["くら", "くろま"],
    "jlpt": 4,
    "unicode": "8eca",
    "heisig_en": "car"
  },
  {
    "kanji": "手",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["hand"],
    "kun_readings": ["て", "て-", "-て", "た-"],
    "on_readings": ["シュ", "ズ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "624b",
    "heisig_en": "hand"
  },
  {
    "kanji": "十",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["ten"],
    "kun_readings": ["とお", "と"],
    "on_readings": ["ジュウ", "ジッ", "ジュッ"],
    "name_readings": [
      "い",
      "か",
      "ぎ",
      "さ",
      "し",
      "そ",
      "そう",
      "ち",
      "とう",
      "ね",
      "ま",
      "る",
      "わ"
    ],
    "jlpt": 4,
    "unicode": "5341",
    "heisig_en": "ten"
  },
  {
    "kanji": "出",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["exit", "leave", "go out", "come out", "put out", "protrude"],
    "kun_readings": ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
    "on_readings": ["シュツ", "スイ"],
    "name_readings": ["いず", "いづ", "いで", "じ", "すっ", "すつ", "てん"],
    "jlpt": 4,
    "unicode": "51fa",
    "heisig_en": "exit"
  },
  {
    "kanji": "女",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["woman", "female"],
    "kun_readings": ["おんな", "め"],
    "on_readings": ["ジョ", "ニョ", "ニョウ"],
    "name_readings": ["おな", "た", "つき", "な"],
    "jlpt": 4,
    "unicode": "5973",
    "heisig_en": "woman"
  },
  {
    "kanji": "小",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["little", "small"],
    "kun_readings": ["ちい.さい", "こ-", "お-", "さ-"],
    "on_readings": ["ショウ"],
    "name_readings": ["いさら", "こう", "さざ", "しゃお", "ちいさ"],
    "jlpt": 4,
    "unicode": "5c0f",
    "heisig_en": "little"
  },
  {
    "kanji": "上",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["above", "up"],
    "kun_readings": [
      "うえ",
      "-うえ",
      "うわ-",
      "かみ",
      "あ.げる",
      "-あ.げる",
      "あ.がる",
      "-あ.がる",
      "あ.がり",
      "-あ.がり",
      "のぼ.る",
      "のぼ.り",
      "のぼ.せる",
      "のぼ.す",
      "たてまつ.る"
    ],
    "on_readings": ["ジョウ", "ショウ", "シャン"],
    "name_readings": [
      "あおい",
      "あげ",
      "い",
      "か",
      "かき",
      "かず",
      "かん",
      "こう",
      "のぼり",
      "ほつ"
    ],
    "jlpt": 4,
    "unicode": "4e0a",
    "heisig_en": "above"
  },
  {
    "kanji": "森",
    "grade": 1,
    "stroke_count": 12,
    "meanings": ["forest", "woods"],
    "kun_readings": ["もり"],
    "on_readings": ["シン"],
    "name_readings": ["もと"],
    "jlpt": 3,
    "unicode": "68ee",
    "heisig_en": "forest"
  },
  {
    "kanji": "人",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["person"],
    "kun_readings": ["ひと", "-り", "-と"],
    "on_readings": ["ジン", "ニン"],
    "name_readings": ["じ", "と", "ね", "ひこ", "ふみ"],
    "jlpt": 4,
    "unicode": "4eba",
    "heisig_en": "person"
  },
  {
    "kanji": "水",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["water"],
    "kun_readings": ["みず", "みず-"],
    "on_readings": ["スイ"],
    "name_readings": ["うず", "ずみ", "つ", "ど", "み", "みさ", "みつ", "みな", "みん"],
    "jlpt": 4,
    "unicode": "6c34",
    "heisig_en": "water"
  },
  {
    "kanji": "正",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["correct", "justice", "righteous", "10**40"],
    "kun_readings": ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
    "on_readings": ["セイ", "ショウ"],
    "name_readings": ["おお", "くに", "ま", "まさし", "ただし"],
    "jlpt": 3,
    "unicode": "6b63",
    "heisig_en": "correct"
  },
  {
    "kanji": "生",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["life", "genuine", "birth"],
    "kun_readings": [
      "い.きる",
      "い.かす",
      "い.ける",
      "う.まれる",
      "うま.れる",
      "う.まれ",
      "うまれ",
      "う.む",
      "お.う",
      "は.える",
      "は.やす",
      "き",
      "なま",
      "なま-",
      "な.る",
      "な.す",
      "む.す",
      "-う"
    ],
    "on_readings": ["セイ", "ショウ"],
    "name_readings": [
      "あさ",
      "いき",
      "いく",
      "いけ",
      "うぶ",
      "うまい",
      "え",
      "おい",
      "ぎゅう",
      "くるみ",
      "ごせ",
      "さ",
      "じょう",
      "すぎ",
      "そ",
      "そう",
      "ちる",
      "なば",
      "にう",
      "にゅう",
      "ふ",
      "み",
      "もう",
      "よい",
      "りゅう"
    ],
    "jlpt": 4,
    "unicode": "751f",
    "heisig_en": "life"
  },
  {
    "kanji": "青",
    "grade": 1,
    "stroke_count": 8,
    "meanings": ["blue", "green"],
    "kun_readings": ["あお", "あお-", "あお.い"],
    "on_readings": ["セイ", "ショウ"],
    "name_readings": ["お"],
    "jlpt": 3,
    "unicode": "9752",
    "heisig_en": "blue"
  },
  {
    "kanji": "石",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["stone"],
    "kun_readings": ["いし"],
    "on_readings": ["セキ", "シャク", "コク"],
    "name_readings": ["いさ", "いす", "いわ", "し", "せっく", "と"],
    "jlpt": 2,
    "unicode": "77f3",
    "heisig_en": "stone"
  },
  {
    "kanji": "赤",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["red"],
    "kun_readings": ["あか", "あか-", "あか.い", "あか.らむ", "あか.らめる"],
    "on_readings": ["セキ", "シャク"],
    "name_readings": ["あ", "あこ", "あま"],
    "jlpt": 3,
    "unicode": "8d64",
    "heisig_en": "red"
  },
  {
    "kanji": "先",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["before", "ahead", "previous", "future", "precedence"],
    "kun_readings": ["さき", "ま.ず"],
    "on_readings": ["セン"],
    "name_readings": ["ぽん"],
    "jlpt": 4,
    "unicode": "5148",
    "heisig_en": "before"
  },
  {
    "kanji": "千",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["thousand"],
    "kun_readings": ["ち"],
    "on_readings": ["セン"],
    "name_readings": ["かず", "ゆき"],
    "jlpt": 4,
    "unicode": "5343",
    "heisig_en": "thousand"
  },
  {
    "kanji": "川",
    "grade": 1,
    "stroke_count": 3,
    "meanings": [
      "stream",
      "river",
      "river or three-stroke river radical (no. 47)"
    ],
    "kun_readings": ["かわ"],
    "on_readings": ["セン"],
    "name_readings": ["か", "こ", "さわ"],
    "jlpt": 4,
    "unicode": "5ddd",
    "heisig_en": "stream"
  },
  {
    "kanji": "早",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["early", "fast"],
    "kun_readings": ["はや.い", "はや", "はや-", "はや.まる", "はや.める", "さ-"],
    "on_readings": ["ソウ", "サッ"],
    "name_readings": ["さか", "さわ", "そ", "わ"],
    "jlpt": 3,
    "unicode": "65e9",
    "heisig_en": "early"
  },
  {
    "kanji": "草",
    "grade": 1,
    "stroke_count": 9,
    "meanings": ["grass", "weeds", "herbs", "pasture", "write", "draft"],
    "kun_readings": ["くさ", "くさ-", "-ぐさ"],
    "on_readings": ["ソウ"],
    "name_readings": ["そ", "や"],
    "jlpt": 2,
    "unicode": "8349",
    "heisig_en": "grass"
  },
  {
    "kanji": "足",
    "grade": 1,
    "stroke_count": 7,
    "meanings": [
      "leg",
      "foot",
      "be sufficient",
      "counter for pairs of footwear"
    ],
    "kun_readings": ["あし", "た.りる", "た.る", "た.す"],
    "on_readings": ["ソク"],
    "name_readings": ["あ", "あす", "おす", "たらし"],
    "jlpt": 4,
    "unicode": "8db3",
    "heisig_en": "leg"
  },
  {
    "kanji": "村",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["village", "town"],
    "kun_readings": ["むら"],
    "on_readings": ["ソン"],
    "name_readings": ["え", "むた", "ら"],
    "jlpt": 3,
    "unicode": "6751",
    "heisig_en": "town"
  },
  {
    "kanji": "大",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["large", "big"],
    "kun_readings": ["おお-", "おお.きい", "-おお.いに"],
    "on_readings": ["ダイ", "タイ"],
    "name_readings": [
      "うふ",
      "お",
      "おう",
      "た",
      "たかし",
      "とも",
      "はじめ",
      "ひろ",
      "ひろし",
      "まさ",
      "まさる",
      "もと",
      "わ"
    ],
    "jlpt": 4,
    "unicode": "5927",
    "heisig_en": "large"
  },
  {
    "kanji": "男",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["male"],
    "kun_readings": ["おとこ", "お"],
    "on_readings": ["ダン", "ナン"],
    "name_readings": ["み"],
    "jlpt": 4,
    "unicode": "7537",
    "heisig_en": "male/man"
  },
  {
    "kanji": "竹",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["bamboo"],
    "kun_readings": ["たけ"],
    "on_readings": ["チク"],
    "name_readings": ["たか"],
    "jlpt": 2,
    "unicode": "7af9",
    "heisig_en": "bamboo"
  },
  {
    "kanji": "中",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["in", "inside", "middle", "mean", "center"],
    "kun_readings": ["なか", "うち", "あた.る"],
    "on_readings": ["チュウ"],
    "name_readings": ["あたる", "かなえ"],
    "jlpt": 4,
    "unicode": "4e2d",
    "heisig_en": "in"
  },
  {
    "kanji": "虫",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["insect", "bug", "temper"],
    "kun_readings": ["むし"],
    "on_readings": ["チュウ", "キ"],
    "name_readings": ["む"],
    "jlpt": 2,
    "unicode": "866b",
    "heisig_en": "insect"
  },
  {
    "kanji": "町",
    "grade": 1,
    "stroke_count": 7,
    "meanings": ["town", "village", "block", "street"],
    "kun_readings": ["まち"],
    "on_readings": ["チョウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "753a",
    "heisig_en": "village"
  },
  {
    "kanji": "天",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["heavens", "sky", "imperial"],
    "kun_readings": ["あまつ", "あめ", "あま-"],
    "on_readings": ["テン"],
    "name_readings": ["あき", "あも", "た", "たかし", "て", "なま"],
    "jlpt": 4,
    "unicode": "5929",
    "heisig_en": "heavens"
  },
  {
    "kanji": "田",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["rice field", "rice paddy"],
    "kun_readings": ["た"],
    "on_readings": ["デン"],
    "name_readings": ["いなか", "おか", "たん", "で", "とう", "や"],
    "jlpt": 3,
    "unicode": "7530",
    "heisig_en": "rice field"
  },
  {
    "kanji": "土",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["soil", "earth", "ground", "Turkey"],
    "kun_readings": ["つち"],
    "on_readings": ["ド", "ト"],
    "name_readings": ["つ", "つく", "は", "ひじ"],
    "jlpt": 4,
    "unicode": "571f",
    "heisig_en": "soil"
  },
  {
    "kanji": "二",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["two", "two radical (no. 7)"],
    "kun_readings": ["ふた", "ふた.つ", "ふたたび"],
    "on_readings": ["ニ", "ジ"],
    "name_readings": ["おと", "つぐ", "つぎ", "にい", "は", "ふ", "ふたつ", "ふだ", "わ"],
    "jlpt": 4,
    "unicode": "4e8c",
    "heisig_en": "two"
  },
  {
    "kanji": "日",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["day", "sun", "Japan", "counter for days"],
    "kun_readings": ["ひ", "-び", "-か"],
    "on_readings": ["ニチ", "ジツ"],
    "name_readings": [
      "あ",
      "あき",
      "いる",
      "く",
      "くさ",
      "こう",
      "す",
      "たち",
      "に",
      "にっ",
      "につ",
      "へ"
    ],
    "jlpt": 4,
    "unicode": "65e5",
    "heisig_en": "day"
  },
  {
    "kanji": "入",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["enter", "insert"],
    "kun_readings": ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
    "on_readings": ["ニュウ", "ジュ"],
    "name_readings": ["いり", "いる", "に", "の", "りり"],
    "jlpt": 4,
    "unicode": "5165",
    "heisig_en": "enter"
  },
  {
    "kanji": "年",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["year", "counter for years"],
    "kun_readings": ["とし"],
    "on_readings": ["ネン"],
    "name_readings": ["ね"],
    "jlpt": 4,
    "unicode": "5e74",
    "heisig_en": "year"
  },
  {
    "kanji": "白",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["white"],
    "kun_readings": ["しろ", "しら-", "しろ.い"],
    "on_readings": ["ハク", "ビャク"],
    "name_readings": ["あき", "か", "はっ"],
    "jlpt": 4,
    "unicode": "767d",
    "heisig_en": "white"
  },
  {
    "kanji": "八",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["eight", "eight radical (no. 12)"],
    "kun_readings": ["や", "や.つ", "やっ.つ", "よう"],
    "on_readings": ["ハチ"],
    "name_readings": ["な", "は", "はっ", "はつ", "やち", "やつ"],
    "jlpt": 4,
    "unicode": "516b",
    "heisig_en": "eight"
  },
  {
    "kanji": "百",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["hundred"],
    "kun_readings": ["もも"],
    "on_readings": ["ヒャク", "ビャク"],
    "name_readings": ["お", "ど", "どう", "なり", "ひゃっ", "ひゅく", "も", "もんど", "ゆ"],
    "jlpt": 4,
    "unicode": "767e",
    "heisig_en": "hundred"
  },
  {
    "kanji": "文",
    "grade": 1,
    "stroke_count": 4,
    "meanings": [
      "sentence",
      "literature",
      "style",
      "art",
      "decoration",
      "figures",
      "plan",
      "literary radical (no. 67)"
    ],
    "kun_readings": ["ふみ", "あや"],
    "on_readings": ["ブン", "モン"],
    "name_readings": ["かざり", "ふ", "も"],
    "jlpt": 3,
    "unicode": "6587",
    "heisig_en": "sentence"
  },
  {
    "kanji": "本",
    "grade": 1,
    "stroke_count": 5,
    "meanings": [
      "book",
      "present",
      "main",
      "origin",
      "true",
      "real",
      "counter for long cylindrical things"
    ],
    "kun_readings": ["もと"],
    "on_readings": ["ホン"],
    "name_readings": ["まと", "ごう"],
    "jlpt": 4,
    "unicode": "672c",
    "heisig_en": "book"
  },
  {
    "kanji": "名",
    "grade": 1,
    "stroke_count": 6,
    "meanings": ["name", "noted", "distinguished", "reputation"],
    "kun_readings": ["な", "-な"],
    "on_readings": ["メイ", "ミョウ"],
    "name_readings": ["と"],
    "jlpt": 4,
    "unicode": "540d",
    "heisig_en": "name"
  },
  {
    "kanji": "木",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["tree", "wood"],
    "kun_readings": ["き", "こ-"],
    "on_readings": ["ボク", "モク"],
    "name_readings": ["ぐ", "も", "もと"],
    "jlpt": 4,
    "unicode": "6728",
    "heisig_en": "tree"
  },
  {
    "kanji": "目",
    "grade": 1,
    "stroke_count": 5,
    "meanings": [
      "eye",
      "class",
      "look",
      "insight",
      "experience",
      "care",
      "favor"
    ],
    "kun_readings": ["め", "-め", "ま-"],
    "on_readings": ["モク", "ボク"],
    "name_readings": ["さかん", "さがん", "さっか", "さつか"],
    "jlpt": 4,
    "unicode": "76ee",
    "heisig_en": "eye"
  },
  {
    "kanji": "夕",
    "grade": 1,
    "stroke_count": 3,
    "meanings": ["evening"],
    "kun_readings": ["ゆう"],
    "on_readings": ["セキ"],
    "name_readings": ["ゆ"],
    "jlpt": 3,
    "unicode": "5915",
    "heisig_en": "evening"
  },
  {
    "kanji": "立",
    "grade": 1,
    "stroke_count": 5,
    "meanings": ["stand up", "rise", "set up", "erect"],
    "kun_readings": [
      "た.つ",
      "-た.つ",
      "た.ち-",
      "た.てる",
      "-た.てる",
      "た.て-",
      "たて-",
      "-た.て",
      "-だ.て",
      "-だ.てる"
    ],
    "on_readings": ["リツ", "リュウ", "リットル"],
    "name_readings": ["たち", "たっ", "たつ", "だて", "つい"],
    "jlpt": 4,
    "unicode": "7acb",
    "heisig_en": "stand up"
  },
  {
    "kanji": "力",
    "grade": 1,
    "stroke_count": 2,
    "meanings": ["power", "strength", "strong", "strain", "bear up", "exert"],
    "kun_readings": ["ちから"],
    "on_readings": ["リョク", "リキ", "リイ"],
    "name_readings": ["じから", "つとむ"],
    "jlpt": 3,
    "unicode": "529b",
    "heisig_en": "power"
  },
  {
    "kanji": "林",
    "grade": 1,
    "stroke_count": 8,
    "meanings": ["grove", "forest"],
    "kun_readings": ["はやし"],
    "on_readings": ["リン"],
    "name_readings": ["し"],
    "jlpt": 3,
    "unicode": "6797",
    "heisig_en": "grove"
  },
  {
    "kanji": "六",
    "grade": 1,
    "stroke_count": 4,
    "meanings": ["six"],
    "kun_readings": ["む", "む.つ", "むっ.つ", "むい"],
    "on_readings": ["ロク", "リク"],
    "name_readings": ["く", "むつ", "ろっ", "ろつ"],
    "jlpt": 4,
    "unicode": "516d",
    "heisig_en": "six"
  }
];

List grade2Kanjis = [
  {
    "kanji": "引",
    "grade": 2,
    "stroke_count": 4,
    "meanings": [
      "pull",
      "tug",
      "jerk",
      "admit",
      "install",
      "quote",
      "refer to"
    ],
    "kun_readings": ["ひ.く", "ひ.き", "ひ.き-", "-び.き", "ひ.ける"],
    "on_readings": ["イン"],
    "name_readings": ["いな", "ひき", "ひけ", "びき"],
    "jlpt": 3,
    "unicode": "5f15",
    "heisig_en": "pull"
  },
  {
    "kanji": "羽",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["feathers", "counter for birds, rabbits"],
    "kun_readings": ["は", "わ", "はね"],
    "on_readings": ["ウ"],
    "name_readings": ["しゅう", "ば"],
    "jlpt": 2,
    "unicode": "7fbd",
    "heisig_en": "feathers"
  },
  {
    "kanji": "雲",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["cloud"],
    "kun_readings": ["くも", "-ぐも"],
    "on_readings": ["ウン"],
    "name_readings": ["き", "ずも", "のめ"],
    "jlpt": 2,
    "unicode": "96f2",
    "heisig_en": "cloud"
  },
  {
    "kanji": "園",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["park", "garden", "yard", "farm"],
    "kun_readings": ["その"],
    "on_readings": ["エン"],
    "name_readings": ["おん", "ぞの"],
    "jlpt": 2,
    "unicode": "5712",
    "heisig_en": "park"
  },
  {
    "kanji": "遠",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["distant", "far"],
    "kun_readings": ["とお.い"],
    "on_readings": ["エン", "オン"],
    "name_readings": ["お", "おに", "ど", "どお"],
    "jlpt": 3,
    "unicode": "9060",
    "heisig_en": "distant"
  },
  {
    "kanji": "黄",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["yellow"],
    "kun_readings": ["き", "こ-"],
    "on_readings": ["コウ", "オウ"],
    "name_readings": ["うい", "れい"],
    "jlpt": 2,
    "unicode": "9ec4",
    "heisig_en": "yellow"
  },
  {
    "kanji": "何",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["what"],
    "kun_readings": ["なに", "なん", "なに-", "なん-"],
    "on_readings": ["カ"],
    "name_readings": ["あが"],
    "jlpt": 4,
    "unicode": "4f55",
    "heisig_en": "what"
  },
  {
    "kanji": "夏",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["summer"],
    "kun_readings": ["なつ"],
    "on_readings": ["カ", "ガ", "ゲ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "590f",
    "heisig_en": "summer"
  },
  {
    "kanji": "家",
    "grade": 2,
    "stroke_count": 10,
    "meanings": [
      "house",
      "home",
      "family",
      "professional",
      "expert",
      "performer"
    ],
    "kun_readings": ["いえ", "や", "うち"],
    "on_readings": ["カ", "ケ"],
    "name_readings": ["あり", "え", "く", "つか", "べ"],
    "jlpt": 3,
    "unicode": "5bb6",
    "heisig_en": "house"
  },
  {
    "kanji": "科",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["department", "course", "section"],
    "kun_readings": [],
    "on_readings": ["カ"],
    "name_readings": ["しな"],
    "jlpt": 2,
    "unicode": "79d1",
    "heisig_en": "department"
  },
  {
    "kanji": "歌",
    "grade": 2,
    "stroke_count": 14,
    "meanings": ["song", "sing"],
    "kun_readings": ["うた", "うた.う"],
    "on_readings": ["カ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "6b4c",
    "heisig_en": "song"
  },
  {
    "kanji": "画",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["brush-stroke", "picture"],
    "kun_readings": ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
    "on_readings": ["ガ", "カク", "エ", "カイ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "753b",
    "heisig_en": "brush stroke"
  },
  {
    "kanji": "会",
    "grade": 2,
    "stroke_count": 6,
    "meanings": [
      "meeting",
      "meet",
      "party",
      "association",
      "interview",
      "join"
    ],
    "kun_readings": ["あ.う", "あ.わせる", "あつ.まる"],
    "on_readings": ["カイ", "エ"],
    "name_readings": ["あい", "い"],
    "jlpt": 4,
    "unicode": "4f1a",
    "heisig_en": "meeting"
  },
  {
    "kanji": "回",
    "grade": 2,
    "stroke_count": 6,
    "meanings": [
      "-times",
      "round",
      "game",
      "revolve",
      "counter for occurrences"
    ],
    "kun_readings": [
      "まわ.る",
      "-まわ.る",
      "-まわ.り",
      "まわ.す",
      "-まわ.す",
      "まわ.し-",
      "-まわ.し",
      "もとお.る",
      "か.える"
    ],
    "on_readings": ["カイ", "エ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "56de",
    "heisig_en": "-times"
  },
  {
    "kanji": "海",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["sea", "ocean"],
    "kun_readings": ["うみ"],
    "on_readings": ["カイ"],
    "name_readings": [
      "あ",
      "あま",
      "うな",
      "うん",
      "え",
      "か",
      "た",
      "ひろ",
      "ひろし",
      "ぶ",
      "まち",
      "まま",
      "み",
      "め",
      "わたる"
    ],
    "jlpt": 3,
    "unicode": "6d77",
    "heisig_en": "sea"
  },
  {
    "kanji": "絵",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["picture", "drawing", "painting", "sketch"],
    "kun_readings": [],
    "on_readings": ["カイ", "エ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "7d75",
    "heisig_en": "picture"
  },
  {
    "kanji": "外",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["outside"],
    "kun_readings": ["そと", "ほか", "はず.す", "はず.れる", "と-"],
    "on_readings": ["ガイ", "ゲ"],
    "name_readings": ["うい", "け", "ふか"],
    "jlpt": 4,
    "unicode": "5916",
    "heisig_en": "outside"
  },
  {
    "kanji": "角",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["angle", "corner", "square", "horn", "antlers"],
    "kun_readings": ["かど", "つの"],
    "on_readings": ["カク"],
    "name_readings": ["い", "す", "すみ", "ずみ", "ふさ"],
    "jlpt": 2,
    "unicode": "89d2",
    "heisig_en": "angle"
  },
  {
    "kanji": "楽",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["music", "comfort", "ease"],
    "kun_readings": ["たの.しい", "たの.しむ", "この.む"],
    "on_readings": ["ガク", "ラク", "ゴウ"],
    "name_readings": ["さ", "た", "やす", "ら"],
    "jlpt": 3,
    "unicode": "697d",
    "heisig_en": "music"
  },
  {
    "kanji": "活",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["lively", "resuscitation", "being helped", "living"],
    "kun_readings": ["い.きる", "い.かす", "い.ける"],
    "on_readings": ["カツ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "6d3b",
    "heisig_en": "lively"
  },
  {
    "kanji": "間",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["interval", "space"],
    "kun_readings": ["あいだ", "ま", "あい"],
    "on_readings": ["カン", "ケン"],
    "name_readings": ["ちか", "は", "はざ", "はし"],
    "jlpt": 4,
    "unicode": "9593",
    "heisig_en": "interval"
  },
  {
    "kanji": "丸",
    "grade": 2,
    "stroke_count": 3,
    "meanings": [
      "round",
      "full (month)",
      "perfection",
      "-ship",
      "pills",
      "make round",
      "roll up",
      "curl up",
      "seduce",
      "explain away"
    ],
    "kun_readings": ["まる", "まる.める", "まる.い"],
    "on_readings": ["ガン"],
    "name_readings": ["ま", "わ", "わに"],
    "jlpt": 2,
    "unicode": "4e38",
    "heisig_en": "round"
  },
  {
    "kanji": "岩",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["boulder", "rock", "cliff"],
    "kun_readings": ["いわ"],
    "on_readings": ["ガン"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "5ca9",
    "heisig_en": "boulder"
  },
  {
    "kanji": "顔",
    "grade": 2,
    "stroke_count": 18,
    "meanings": ["face", "expression"],
    "kun_readings": ["かお"],
    "on_readings": ["ガン"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "9854",
    "heisig_en": "face"
  },
  {
    "kanji": "帰",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["homecoming", "arrive at", "lead to", "result in"],
    "kun_readings": ["かえ.る", "かえ.す", "おく.る", "とつ.ぐ"],
    "on_readings": ["キ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5e30",
    "heisig_en": "homecoming"
  },
  {
    "kanji": "汽",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["vapor", "steam"],
    "kun_readings": [],
    "on_readings": ["キ"],
    "name_readings": [],
    "jlpt": 1,
    "unicode": "6c7d",
    "heisig_en": "vapor"
  },
  {
    "kanji": "記",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["scribe", "account", "narrative"],
    "kun_readings": ["しる.す"],
    "on_readings": ["キ"],
    "name_readings": ["のり"],
    "jlpt": 2,
    "unicode": "8a18",
    "heisig_en": "scribe"
  },
  {
    "kanji": "弓",
    "grade": 2,
    "stroke_count": 3,
    "meanings": ["bow", "bow (archery, violin)"],
    "kun_readings": ["ゆみ"],
    "on_readings": ["キュウ"],
    "name_readings": ["こ", "ゆ"],
    "jlpt": 1,
    "unicode": "5f13",
    "heisig_en": "bow"
  },
  {
    "kanji": "牛",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["cow"],
    "kun_readings": ["うし"],
    "on_readings": ["ギュウ"],
    "name_readings": ["うじ", "ご"],
    "jlpt": 3,
    "unicode": "725b",
    "heisig_en": "cow"
  },
  {
    "kanji": "魚",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["fish"],
    "kun_readings": ["うお", "さかな", "-ざかな"],
    "on_readings": ["ギョ"],
    "name_readings": ["い"],
    "jlpt": 4,
    "unicode": "9b5a",
    "heisig_en": "fish"
  },
  {
    "kanji": "京",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["capital", "10**16"],
    "kun_readings": ["みやこ"],
    "on_readings": ["キョウ", "ケイ", "キン"],
    "name_readings": ["たか"],
    "jlpt": 3,
    "unicode": "4eac",
    "heisig_en": "capital"
  },
  {
    "kanji": "強",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["strong"],
    "kun_readings": ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
    "on_readings": ["キョウ", "ゴウ"],
    "name_readings": ["すね"],
    "jlpt": 3,
    "unicode": "5f37",
    "heisig_en": "strong"
  },
  {
    "kanji": "教",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["teach", "faith", "doctrine"],
    "kun_readings": ["おし.える", "おそ.わる"],
    "on_readings": ["キョウ"],
    "name_readings": ["のり", "ひさ"],
    "jlpt": 3,
    "unicode": "6559",
    "heisig_en": "teach"
  },
  {
    "kanji": "近",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["near", "early", "akin", "tantamount"],
    "kun_readings": ["ちか.い"],
    "on_readings": ["キン", "コン"],
    "name_readings": ["おう", "おお", "この"],
    "jlpt": 3,
    "unicode": "8fd1",
    "heisig_en": "near"
  },
  {
    "kanji": "兄",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["elder brother", "big brother"],
    "kun_readings": ["あに"],
    "on_readings": ["ケイ", "キョウ"],
    "name_readings": ["え", "せ", "よし"],
    "jlpt": 3,
    "unicode": "5144",
    "heisig_en": "elder brother"
  },
  {
    "kanji": "形",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["shape", "form", "style"],
    "kun_readings": ["かた", "-がた", "かたち", "なり"],
    "on_readings": ["ケイ", "ギョウ"],
    "name_readings": ["ち"],
    "jlpt": 2,
    "unicode": "5f62",
    "heisig_en": "shape"
  },
  {
    "kanji": "計",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["plot", "plan", "scheme", "measure"],
    "kun_readings": ["はか.る", "はか.らう"],
    "on_readings": ["ケイ"],
    "name_readings": ["え", "かず", "け"],
    "jlpt": 3,
    "unicode": "8a08",
    "heisig_en": "plot"
  },
  {
    "kanji": "元",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["beginning", "former time", "origin"],
    "kun_readings": ["もと"],
    "on_readings": ["ゲン", "ガン"],
    "name_readings": ["ちか", "はじめ", "はる", "ゆき", "よし"],
    "jlpt": 3,
    "unicode": "5143",
    "heisig_en": "beginning"
  },
  {
    "kanji": "原",
    "grade": 2,
    "stroke_count": 10,
    "meanings": [
      "meadow",
      "original",
      "primitive",
      "field",
      "plain",
      "prairie",
      "tundra",
      "wilderness"
    ],
    "kun_readings": ["はら"],
    "on_readings": ["ゲン"],
    "name_readings": ["た", "ばる", "ら", "わた", "わら"],
    "jlpt": 2,
    "unicode": "539f",
    "heisig_en": "meadow"
  },
  {
    "kanji": "言",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["say", "word"],
    "kun_readings": ["い.う", "こと"],
    "on_readings": ["ゲン", "ゴン"],
    "name_readings": ["とき"],
    "jlpt": 4,
    "unicode": "8a00",
    "heisig_en": "say"
  },
  {
    "kanji": "古",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["old"],
    "kun_readings": ["ふる.い", "ふる-", "-ふる.す"],
    "on_readings": ["コ"],
    "name_readings": ["ふゆ"],
    "jlpt": 4,
    "unicode": "53e4",
    "heisig_en": "old"
  },
  {
    "kanji": "戸",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["door", "counter for houses", "door radical (no. 63)"],
    "kun_readings": ["と"],
    "on_readings": ["コ"],
    "name_readings": ["え", "へ"],
    "jlpt": 2,
    "unicode": "6238",
    "heisig_en": "door"
  },
  {
    "kanji": "午",
    "grade": 2,
    "stroke_count": 4,
    "meanings": [
      "noon",
      "sign of the horse",
      "11AM-1PM",
      "seventh sign of Chinese zodiac"
    ],
    "kun_readings": ["うま"],
    "on_readings": ["ゴ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "5348",
    "heisig_en": "noon"
  },
  {
    "kanji": "後",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["behind", "back", "later"],
    "kun_readings": ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
    "on_readings": ["ゴ", "コウ"],
    "name_readings": ["こし", "し", "しい", "しり"],
    "jlpt": 4,
    "unicode": "5f8c",
    "heisig_en": "behind"
  },
  {
    "kanji": "語",
    "grade": 2,
    "stroke_count": 14,
    "meanings": ["word", "speech", "language"],
    "kun_readings": ["かた.る", "かた.らう"],
    "on_readings": ["ゴ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "8a9e",
    "heisig_en": "word"
  },
  {
    "kanji": "交",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["mingle", "mixing", "association", "coming & going"],
    "kun_readings": [
      "まじ.わる",
      "まじ.える",
      "ま.じる",
      "まじ.る",
      "ま.ざる",
      "ま.ぜる",
      "-か.う",
      "か.わす",
      "かわ.す",
      "こもごも"
    ],
    "on_readings": ["コウ"],
    "name_readings": ["かた"],
    "jlpt": 2,
    "unicode": "4ea4",
    "heisig_en": "mingle"
  },
  {
    "kanji": "光",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["ray", "light"],
    "kun_readings": ["ひか.る", "ひかり"],
    "on_readings": ["コウ"],
    "name_readings": ["あき", "あきら", "こお", "てる", "ひこ", "み", "みつ"],
    "jlpt": 3,
    "unicode": "5149",
    "heisig_en": "ray"
  },
  {
    "kanji": "公",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["public", "prince", "official", "governmental"],
    "kun_readings": ["おおやけ"],
    "on_readings": ["コウ", "ク"],
    "name_readings": ["あきら", "き", "きみ", "きん", "たか", "ただし", "とも", "ひろ", "まさ"],
    "jlpt": 2,
    "unicode": "516c",
    "heisig_en": "public"
  },
  {
    "kanji": "工",
    "grade": 2,
    "stroke_count": 3,
    "meanings": ["craft", "construction", "katakana e radical (no. 48)"],
    "kun_readings": [],
    "on_readings": ["コウ", "ク", "グ"],
    "name_readings": ["もく"],
    "jlpt": 3,
    "unicode": "5de5",
    "heisig_en": "craft"
  },
  {
    "kanji": "広",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["wide", "broad", "spacious"],
    "kun_readings": ["ひろ.い", "ひろ.まる", "ひろ.める", "ひろ.がる", "ひろ.げる"],
    "on_readings": ["コウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5e83",
    "heisig_en": "wide"
  },
  {
    "kanji": "考",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["consider", "think over"],
    "kun_readings": ["かんが.える", "かんが.え"],
    "on_readings": ["コウ"],
    "name_readings": ["たか"],
    "jlpt": 3,
    "unicode": "8003",
    "heisig_en": "consider"
  },
  {
    "kanji": "行",
    "grade": 2,
    "stroke_count": 6,
    "meanings": [
      "going",
      "journey",
      "carry out",
      "conduct",
      "act",
      "line",
      "row",
      "bank"
    ],
    "kun_readings": [
      "い.く",
      "ゆ.く",
      "-ゆ.き",
      "-ゆき",
      "-い.き",
      "-いき",
      "おこな.う",
      "おこ.なう"
    ],
    "on_readings": ["コウ", "ギョウ", "アン"],
    "name_readings": ["いく", "なみ", "なめ", "みち", "ゆき", "ゆく"],
    "jlpt": 4,
    "unicode": "884c",
    "heisig_en": "going"
  },
  {
    "kanji": "高",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["tall", "high", "expensive"],
    "kun_readings": ["たか.い", "たか", "-だか", "たか.まる", "たか.める"],
    "on_readings": ["コウ"],
    "name_readings": ["か", "こ", "じょい", "た", "はか"],
    "jlpt": 4,
    "unicode": "9ad8",
    "heisig_en": "tall"
  },
  {
    "kanji": "合",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["fit", "suit", "join", "0.1"],
    "kun_readings": [
      "あ.う",
      "-あ.う",
      "あ.い",
      "あい-",
      "-あ.い",
      "-あい",
      "あ.わす",
      "あ.わせる",
      "-あ.わせる"
    ],
    "on_readings": ["ゴウ", "ガッ", "カッ"],
    "name_readings": [
      "あう",
      "あん",
      "い",
      "か",
      "こう",
      "ごお",
      "に",
      "ね",
      "や",
      "り",
      "わい"
    ],
    "jlpt": 3,
    "unicode": "5408",
    "heisig_en": "fit"
  },
  {
    "kanji": "国",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["country"],
    "kun_readings": ["くに"],
    "on_readings": ["コク"],
    "name_readings": ["くな", "こ"],
    "jlpt": 4,
    "unicode": "56fd",
    "heisig_en": "country"
  },
  {
    "kanji": "黒",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["black"],
    "kun_readings": ["くろ", "くろ.ずむ", "くろ.い"],
    "on_readings": ["コク"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "9ed2",
    "heisig_en": "black"
  },
  {
    "kanji": "今",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["now"],
    "kun_readings": ["いま"],
    "on_readings": ["コン", "キン"],
    "name_readings": ["な"],
    "jlpt": 4,
    "unicode": "4eca",
    "heisig_en": "now"
  },
  {
    "kanji": "才",
    "grade": 2,
    "stroke_count": 3,
    "meanings": ["genius", "years old", "cubic shaku"],
    "kun_readings": [],
    "on_readings": ["サイ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "624d",
    "heisig_en": "genius"
  },
  {
    "kanji": "細",
    "grade": 2,
    "stroke_count": 11,
    "meanings": [
      "dainty",
      "get thin",
      "taper",
      "slender",
      "narrow",
      "detailed",
      "precise"
    ],
    "kun_readings": ["ほそ.い", "ほそ.る", "こま.か", "こま.かい"],
    "on_readings": ["サイ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "7d30",
    "heisig_en": "dainty"
  },
  {
    "kanji": "作",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["make", "production", "prepare", "build"],
    "kun_readings": ["つく.る", "つく.り", "-づく.り"],
    "on_readings": ["サク", "サ"],
    "name_readings": ["くり", "さか", "さっ", "づくり", "とも", "なお", "はぎ", "まさか"],
    "jlpt": 3,
    "unicode": "4f5c",
    "heisig_en": "make"
  },
  {
    "kanji": "算",
    "grade": 2,
    "stroke_count": 14,
    "meanings": ["calculate", "divining", "number", "abacus", "probability"],
    "kun_readings": ["そろ"],
    "on_readings": ["サン"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "7b97",
    "heisig_en": "calculate"
  },
  {
    "kanji": "姉",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["elder sister"],
    "kun_readings": ["あね", "はは"],
    "on_readings": ["シ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "59c9",
    "heisig_en": "elder sister"
  },
  {
    "kanji": "市",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["market", "city", "town"],
    "kun_readings": ["いち"],
    "on_readings": ["シ"],
    "name_readings": ["い", "ち"],
    "jlpt": 3,
    "unicode": "5e02",
    "heisig_en": "market"
  },
  {
    "kanji": "思",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["think"],
    "kun_readings": ["おも.う", "おもえら.く", "おぼ.す"],
    "on_readings": ["シ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "601d",
    "heisig_en": "think"
  },
  {
    "kanji": "止",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["stop", "halt"],
    "kun_readings": [
      "と.まる",
      "-ど.まり",
      "と.める",
      "-と.める",
      "-ど.め",
      "とど.める",
      "とど.め",
      "とど.まる",
      "や.める",
      "や.む",
      "-や.む",
      "よ.す",
      "-さ.す",
      "-さ.し"
    ],
    "on_readings": ["シ"],
    "name_readings": ["どめ"],
    "jlpt": 3,
    "unicode": "6b62",
    "heisig_en": "stop"
  },
  {
    "kanji": "紙",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["paper"],
    "kun_readings": ["かみ"],
    "on_readings": ["シ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "7d19",
    "heisig_en": "paper"
  },
  {
    "kanji": "寺",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["Buddhist temple"],
    "kun_readings": ["てら"],
    "on_readings": ["ジ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "5bfa",
    "heisig_en": "Buddhist temple"
  },
  {
    "kanji": "時",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["time", "hour"],
    "kun_readings": ["とき", "-どき"],
    "on_readings": ["ジ"],
    "name_readings": ["と", "とぎ"],
    "jlpt": 4,
    "unicode": "6642",
    "heisig_en": "time"
  },
  {
    "kanji": "自",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["oneself"],
    "kun_readings": ["みずか.ら", "おの.ずから", "おの.ずと"],
    "on_readings": ["ジ", "シ"],
    "name_readings": ["より"],
    "jlpt": 3,
    "unicode": "81ea",
    "heisig_en": "oneself"
  },
  {
    "kanji": "室",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["room", "apartment", "chamber", "greenhouse", "cellar"],
    "kun_readings": ["むろ"],
    "on_readings": ["シツ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5ba4",
    "heisig_en": "room"
  },
  {
    "kanji": "社",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["company", "firm", "office", "association", "shrine"],
    "kun_readings": ["やしろ"],
    "on_readings": ["シャ"],
    "name_readings": ["こそ"],
    "jlpt": 4,
    "unicode": "793e",
    "heisig_en": "company"
  },
  {
    "kanji": "弱",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["weak", "frail"],
    "kun_readings": ["よわ.い", "よわ.る", "よわ.まる", "よわ.める"],
    "on_readings": ["ジャク"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5f31",
    "heisig_en": "weak"
  },
  {
    "kanji": "首",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["neck", "counter for songs and poems"],
    "kun_readings": ["くび"],
    "on_readings": ["シュ"],
    "name_readings": ["おびと", "こべ", "す"],
    "jlpt": 3,
    "unicode": "9996",
    "heisig_en": "neck"
  },
  {
    "kanji": "秋",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["autumn"],
    "kun_readings": ["あき", "とき"],
    "on_readings": ["シュウ"],
    "name_readings": ["あい"],
    "jlpt": 3,
    "unicode": "79cb",
    "heisig_en": "autumn"
  },
  {
    "kanji": "週",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["week"],
    "kun_readings": [],
    "on_readings": ["シュウ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "9031",
    "heisig_en": "week"
  },
  {
    "kanji": "春",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["springtime", "spring (season)"],
    "kun_readings": ["はる"],
    "on_readings": ["シュン"],
    "name_readings": ["あずま", "かす", "すの", "ひ", "わら"],
    "jlpt": 3,
    "unicode": "6625",
    "heisig_en": "springtime"
  },
  {
    "kanji": "書",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["write"],
    "kun_readings": ["か.く", "-が.き", "-がき"],
    "on_readings": ["ショ"],
    "name_readings": ["かき"],
    "jlpt": 4,
    "unicode": "66f8",
    "heisig_en": "write"
  },
  {
    "kanji": "少",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["few", "little"],
    "kun_readings": ["すく.ない", "すこ.し"],
    "on_readings": ["ショウ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "5c11",
    "heisig_en": "few"
  },
  {
    "kanji": "場",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["location", "place"],
    "kun_readings": ["ば"],
    "on_readings": ["ジョウ", "チョウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5834",
    "heisig_en": "location"
  },
  {
    "kanji": "色",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["color"],
    "kun_readings": ["いろ"],
    "on_readings": ["ショク", "シキ"],
    "name_readings": ["しか", "しこ"],
    "jlpt": 3,
    "unicode": "8272",
    "heisig_en": "color"
  },
  {
    "kanji": "食",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["eat", "food"],
    "kun_readings": ["く.う", "く.らう", "た.べる", "は.む"],
    "on_readings": ["ショク", "ジキ"],
    "name_readings": ["ぐい"],
    "jlpt": 4,
    "unicode": "98df",
    "heisig_en": "eat"
  },
  {
    "kanji": "心",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["heart", "mind", "spirit", "heart radical (no. 61)"],
    "kun_readings": ["こころ", "-ごころ"],
    "on_readings": ["シン"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "5fc3",
    "heisig_en": "heart"
  },
  {
    "kanji": "新",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["new"],
    "kun_readings": ["あたら.しい", "あら.た", "あら-", "にい-"],
    "on_readings": ["シン"],
    "name_readings": ["あせ", "あたらし", "し", "に", "にっ", "につ", "よし"],
    "jlpt": 4,
    "unicode": "65b0",
    "heisig_en": "new"
  },
  {
    "kanji": "親",
    "grade": 2,
    "stroke_count": 16,
    "meanings": [
      "parent",
      "intimacy",
      "relative",
      "familiarity",
      "dealer (cards)"
    ],
    "kun_readings": ["おや", "おや-", "した.しい", "した.しむ"],
    "on_readings": ["シン"],
    "name_readings": ["ぎ", "ちか", "のり"],
    "jlpt": 3,
    "unicode": "89aa",
    "heisig_en": "parent"
  },
  {
    "kanji": "図",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["map", "drawing", "plan", "extraordinary", "audacious"],
    "kun_readings": ["え", "はか.る"],
    "on_readings": ["ズ", "ト"],
    "name_readings": ["づ"],
    "jlpt": 3,
    "unicode": "56f3",
    "heisig_en": "map"
  },
  {
    "kanji": "数",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["number", "strength", "fate", "law", "figures"],
    "kun_readings": ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
    "on_readings": ["スウ", "ス", "サク", "ソク", "シュ"],
    "name_readings": ["じゅ"],
    "jlpt": 2,
    "unicode": "6570",
    "heisig_en": "number"
  },
  {
    "kanji": "星",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["star", "spot", "dot", "mark"],
    "kun_readings": ["ほし", "-ぼし"],
    "on_readings": ["セイ", "ショウ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "661f",
    "heisig_en": "star"
  },
  {
    "kanji": "晴",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["clear up"],
    "kun_readings": ["は.れる", "は.れ", "は.れ-", "-ば.れ", "は.らす"],
    "on_readings": ["セイ"],
    "name_readings": ["はる", "はれ"],
    "jlpt": 2,
    "unicode": "6674",
    "heisig_en": "clear up"
  },
  {
    "kanji": "声",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["voice"],
    "kun_readings": ["こえ", "こわ-"],
    "on_readings": ["セイ", "ショウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "58f0",
    "heisig_en": "voice"
  },
  {
    "kanji": "西",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["west", "Spain"],
    "kun_readings": ["にし"],
    "on_readings": ["セイ", "サイ", "ス"],
    "name_readings": ["いり", "ひし", "むら"],
    "jlpt": 4,
    "unicode": "897f",
    "heisig_en": "west"
  },
  {
    "kanji": "切",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["cut", "cutoff", "be sharp"],
    "kun_readings": [
      "き.る",
      "-き.る",
      "き.り",
      "-き.り",
      "-ぎ.り",
      "き.れる",
      "-き.れる",
      "き.れ",
      "-き.れ",
      "-ぎ.れ"
    ],
    "on_readings": ["セツ", "サイ"],
    "name_readings": ["きつ", "きり", "ぎり"],
    "jlpt": 3,
    "unicode": "5207",
    "heisig_en": "cut"
  },
  {
    "kanji": "雪",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["snow"],
    "kun_readings": ["ゆき"],
    "on_readings": ["セツ"],
    "name_readings": ["せっ", "ぶき"],
    "jlpt": 2,
    "unicode": "96ea",
    "heisig_en": "snow"
  },
  {
    "kanji": "線",
    "grade": 2,
    "stroke_count": 15,
    "meanings": ["line", "track"],
    "kun_readings": ["すじ"],
    "on_readings": ["セン"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "7dda",
    "heisig_en": "line"
  },
  {
    "kanji": "船",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["ship", "boat"],
    "kun_readings": ["ふね", "ふな-"],
    "on_readings": ["セン"],
    "name_readings": ["ふ"],
    "jlpt": 2,
    "unicode": "8239",
    "heisig_en": "ship"
  },
  {
    "kanji": "前",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["in front", "before"],
    "kun_readings": ["まえ", "-まえ"],
    "on_readings": ["ゼン"],
    "name_readings": ["さき", "さと", "まい"],
    "jlpt": 4,
    "unicode": "524d",
    "heisig_en": "in front"
  },
  {
    "kanji": "組",
    "grade": 2,
    "stroke_count": 11,
    "meanings": [
      "association",
      "braid",
      "plait",
      "construct",
      "assemble",
      "unite",
      "cooperate",
      "grapple"
    ],
    "kun_readings": ["く.む", "くみ", "-ぐみ"],
    "on_readings": ["ソ"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "7d44",
    "heisig_en": "association"
  },
  {
    "kanji": "走",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["run"],
    "kun_readings": ["はし.る"],
    "on_readings": ["ソウ"],
    "name_readings": ["はしり"],
    "jlpt": 3,
    "unicode": "8d70",
    "heisig_en": "run"
  },
  {
    "kanji": "多",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["many", "frequent", "much"],
    "kun_readings": ["おお.い", "まさ.に", "まさ.る"],
    "on_readings": ["タ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "591a",
    "heisig_en": "many"
  },
  {
    "kanji": "太",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["plump", "thick", "big around"],
    "kun_readings": ["ふと.い", "ふと.る"],
    "on_readings": ["タイ", "タ"],
    "name_readings": ["おお", "たか", "ひろ"],
    "jlpt": 3,
    "unicode": "592a",
    "heisig_en": "plump"
  },
  {
    "kanji": "体",
    "grade": 2,
    "stroke_count": 7,
    "meanings": [
      "body",
      "substance",
      "object",
      "reality",
      "counter for images"
    ],
    "kun_readings": ["からだ", "かたち"],
    "on_readings": ["タイ", "テイ"],
    "name_readings": ["なり"],
    "jlpt": 3,
    "unicode": "4f53",
    "heisig_en": "body"
  },
  {
    "kanji": "台",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["pedestal", "a stand", "counter for machines and vehicles"],
    "kun_readings": ["うてな", "われ", "つかさ"],
    "on_readings": ["ダイ", "タイ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "53f0",
    "heisig_en": "pedestal"
  },
  {
    "kanji": "谷",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["valley"],
    "kun_readings": ["たに", "きわ.まる"],
    "on_readings": ["コク"],
    "name_readings": ["がい", "がえ", "がや", "せ", "たり", "たん", "や"],
    "jlpt": 2,
    "unicode": "8c37",
    "heisig_en": "valley"
  },
  {
    "kanji": "知",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["know", "wisdom"],
    "kun_readings": ["し.る", "し.らせる"],
    "on_readings": ["チ"],
    "name_readings": ["さと", "さとる", "しり", "しれ", "とも", "のり"],
    "jlpt": 3,
    "unicode": "77e5",
    "heisig_en": "know"
  },
  {
    "kanji": "地",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["ground", "earth"],
    "kun_readings": [],
    "on_readings": ["チ", "ジ"],
    "name_readings": ["どま"],
    "jlpt": 3,
    "unicode": "5730",
    "heisig_en": "ground"
  },
  {
    "kanji": "池",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["pond", "cistern", "pool", "reservoir"],
    "kun_readings": ["いけ"],
    "on_readings": ["チ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "6c60",
    "heisig_en": "pond"
  },
  {
    "kanji": "茶",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["tea"],
    "kun_readings": [],
    "on_readings": ["チャ", "サ"],
    "name_readings": ["ちや"],
    "jlpt": 3,
    "unicode": "8336",
    "heisig_en": "tea"
  },
  {
    "kanji": "昼",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["daytime", "noon"],
    "kun_readings": ["ひる"],
    "on_readings": ["チュウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "663c",
    "heisig_en": "daytime"
  },
  {
    "kanji": "朝",
    "grade": 2,
    "stroke_count": 12,
    "meanings": [
      "morning",
      "dynasty",
      "regime",
      "epoch",
      "period",
      "(North) Korea"
    ],
    "kun_readings": ["あさ"],
    "on_readings": ["チョウ"],
    "name_readings": ["あ", "あそ", "ささ", "ちか", "とも"],
    "jlpt": 3,
    "unicode": "671d",
    "heisig_en": "morning"
  },
  {
    "kanji": "長",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["long", "leader", "superior", "senior"],
    "kun_readings": ["なが.い", "おさ"],
    "on_readings": ["チョウ"],
    "name_readings": ["お", "おしゃ", "たかし", "たけ", "な", "は", "ひさ"],
    "jlpt": 4,
    "unicode": "9577",
    "heisig_en": "long"
  },
  {
    "kanji": "鳥",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["bird", "chicken"],
    "kun_readings": ["とり"],
    "on_readings": ["チョウ"],
    "name_readings": ["か", "と", "とっ"],
    "jlpt": 3,
    "unicode": "9ce5",
    "heisig_en": "bird"
  },
  {
    "kanji": "直",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["straightaway", "honesty", "frankness", "fix", "repair"],
    "kun_readings": ["ただ.ちに", "なお.す", "-なお.す", "なお.る", "なお.き", "す.ぐ"],
    "on_readings": ["チョク", "ジキ", "ジカ"],
    "name_readings": ["すぐ", "なお", "のう", "のお"],
    "jlpt": 2,
    "unicode": "76f4",
    "heisig_en": "straightaway"
  },
  {
    "kanji": "通",
    "grade": 2,
    "stroke_count": 10,
    "meanings": [
      "traffic",
      "pass through",
      "avenue",
      "commute",
      "counter for letters, notes, documents, etc."
    ],
    "kun_readings": [
      "とお.る",
      "とお.り",
      "-とお.り",
      "-どお.り",
      "とお.す",
      "とお.し",
      "-どお.し",
      "かよ.う"
    ],
    "on_readings": ["ツウ", "ツ"],
    "name_readings": ["とん", "どうし", "どおり", "みち"],
    "jlpt": 3,
    "unicode": "901a",
    "heisig_en": "traffic"
  },
  {
    "kanji": "弟",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["younger brother", "faithful service to elders"],
    "kun_readings": ["おとうと"],
    "on_readings": ["テイ", "ダイ", "デ"],
    "name_readings": ["て"],
    "jlpt": 3,
    "unicode": "5f1f",
    "heisig_en": "younger brother"
  },
  {
    "kanji": "店",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["store", "shop"],
    "kun_readings": ["みせ", "たな"],
    "on_readings": ["テン"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "5e97",
    "heisig_en": "store"
  },
  {
    "kanji": "点",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["spot", "point", "mark", "speck", "decimal point"],
    "kun_readings": ["つ.ける", "つ.く", "た.てる", "さ.す", "とぼ.す", "とも.す", "ぼち"],
    "on_readings": ["テン"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "70b9",
    "heisig_en": "spot"
  },
  {
    "kanji": "電",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["electricity"],
    "kun_readings": [],
    "on_readings": ["デン"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "96fb",
    "heisig_en": "electricity"
  },
  {
    "kanji": "冬",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["winter"],
    "kun_readings": ["ふゆ"],
    "on_readings": ["トウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "51ac",
    "heisig_en": "winter"
  },
  {
    "kanji": "刀",
    "grade": 2,
    "stroke_count": 2,
    "meanings": ["sword", "saber", "knife"],
    "kun_readings": ["かたな", "そり"],
    "on_readings": ["トウ"],
    "name_readings": ["き", "ち", "と", "わき"],
    "jlpt": 1,
    "unicode": "5200",
    "heisig_en": "sword"
  },
  {
    "kanji": "東",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["east"],
    "kun_readings": ["ひがし"],
    "on_readings": ["トウ"],
    "name_readings": [
      "あい",
      "あがり",
      "あずま",
      "あづま",
      "こ",
      "さき",
      "しの",
      "とお",
      "はる",
      "ひが",
      "もと"
    ],
    "jlpt": 4,
    "unicode": "6771",
    "heisig_en": "east"
  },
  {
    "kanji": "当",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["hit", "right", "appropriate", "himself"],
    "kun_readings": ["あ.たる", "あ.たり", "あ.てる", "あ.て", "まさ.に", "まさ.にべし"],
    "on_readings": ["トウ"],
    "name_readings": ["たい"],
    "jlpt": 2,
    "unicode": "5f53",
    "heisig_en": "hit"
  },
  {
    "kanji": "答",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["solution", "answer"],
    "kun_readings": ["こた.える", "こた.え"],
    "on_readings": ["トウ"],
    "name_readings": ["どう"],
    "jlpt": 3,
    "unicode": "7b54",
    "heisig_en": "solution"
  },
  {
    "kanji": "頭",
    "grade": 2,
    "stroke_count": 16,
    "meanings": ["head", "counter for large animals"],
    "kun_readings": ["あたま", "かしら", "-がしら", "かぶり"],
    "on_readings": ["トウ", "ズ", "ト"],
    "name_readings": ["かみ", "がみ", "ちゃん", "つむり", "づ"],
    "jlpt": 3,
    "unicode": "982d",
    "heisig_en": "head"
  },
  {
    "kanji": "同",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["same", "agree", "equal"],
    "kun_readings": ["おな.じ"],
    "on_readings": ["ドウ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "540c",
    "heisig_en": "same"
  },
  {
    "kanji": "道",
    "grade": 2,
    "stroke_count": 12,
    "meanings": [
      "road-way",
      "street",
      "district",
      "journey",
      "course",
      "moral",
      "teachings"
    ],
    "kun_readings": ["みち", "いう"],
    "on_readings": ["ドウ", "トウ"],
    "name_readings": ["さ", "じ", "ど", "みつ", "おさむ"],
    "jlpt": 4,
    "unicode": "9053",
    "heisig_en": "road-way"
  },
  {
    "kanji": "読",
    "grade": 2,
    "stroke_count": 14,
    "meanings": ["read"],
    "kun_readings": ["よ.む", "-よ.み"],
    "on_readings": ["ドク", "トク", "トウ"],
    "name_readings": ["よみ"],
    "jlpt": 4,
    "unicode": "8aad",
    "heisig_en": "read"
  },
  {
    "kanji": "内",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["inside", "within", "between", "among", "house", "home"],
    "kun_readings": ["うち"],
    "on_readings": ["ナイ", "ダイ"],
    "name_readings": ["いと", "ただ", "ち", "のち"],
    "jlpt": 2,
    "unicode": "5185",
    "heisig_en": "inside"
  },
  {
    "kanji": "南",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["south"],
    "kun_readings": ["みなみ"],
    "on_readings": ["ナン", "ナ"],
    "name_readings": ["なみ", "は", "みな", "みまみ"],
    "jlpt": 4,
    "unicode": "5357",
    "heisig_en": "south"
  },
  {
    "kanji": "肉",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["meat"],
    "kun_readings": ["しし"],
    "on_readings": ["ニク"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "8089",
    "heisig_en": "meat"
  },
  {
    "kanji": "馬",
    "grade": 2,
    "stroke_count": 10,
    "meanings": ["horse"],
    "kun_readings": ["うま", "うま-", "ま"],
    "on_readings": ["バ"],
    "name_readings": ["た", "ばん", "め", "も"],
    "jlpt": 2,
    "unicode": "99ac",
    "heisig_en": "horse"
  },
  {
    "kanji": "買",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["buy"],
    "kun_readings": ["か.う"],
    "on_readings": ["バイ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "8cb7",
    "heisig_en": "buy"
  },
  {
    "kanji": "売",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["sell"],
    "kun_readings": ["う.る", "う.れる"],
    "on_readings": ["バイ"],
    "name_readings": ["うり", "うる", "め"],
    "jlpt": 3,
    "unicode": "58f2",
    "heisig_en": "sell"
  },
  {
    "kanji": "麦",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["barley", "wheat"],
    "kun_readings": ["むぎ"],
    "on_readings": ["バク"],
    "name_readings": [],
    "jlpt": 2,
    "unicode": "9ea6",
    "heisig_en": "barley"
  },
  {
    "kanji": "半",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["half", "middle", "odd number", "semi-", "part-"],
    "kun_readings": ["なか.ば"],
    "on_readings": ["ハン"],
    "name_readings": ["は"],
    "jlpt": 4,
    "unicode": "534a",
    "heisig_en": "half"
  },
  {
    "kanji": "番",
    "grade": 2,
    "stroke_count": 12,
    "meanings": ["turn", "number in a series"],
    "kun_readings": ["つが.い"],
    "on_readings": ["バン"],
    "name_readings": ["は", "ま"],
    "jlpt": 2,
    "unicode": "756a",
    "heisig_en": "turn"
  },
  {
    "kanji": "父",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["father"],
    "kun_readings": ["ちち"],
    "on_readings": ["フ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "7236",
    "heisig_en": "father"
  },
  {
    "kanji": "風",
    "grade": 2,
    "stroke_count": 9,
    "meanings": ["wind", "air", "style", "manner"],
    "kun_readings": ["かぜ", "かざ-", "-かぜ"],
    "on_readings": ["フウ", "フ"],
    "name_readings": ["い", "え"],
    "jlpt": 3,
    "unicode": "98a8",
    "heisig_en": "wind"
  },
  {
    "kanji": "分",
    "grade": 2,
    "stroke_count": 4,
    "meanings": [
      "part",
      "minute of time",
      "segment",
      "share",
      "degree",
      "one's lot",
      "duty",
      "understand",
      "know",
      "rate",
      "1%",
      "chances",
      "shaku/100"
    ],
    "kun_readings": ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
    "on_readings": ["ブン", "フン", "ブ"],
    "name_readings": ["いた", "わけ"],
    "jlpt": 4,
    "unicode": "5206",
    "heisig_en": "part"
  },
  {
    "kanji": "聞",
    "grade": 2,
    "stroke_count": 14,
    "meanings": ["hear", "ask", "listen"],
    "kun_readings": ["き.く", "き.こえる"],
    "on_readings": ["ブン", "モン"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "805e",
    "heisig_en": "hear"
  },
  {
    "kanji": "米",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["rice", "USA", "metre"],
    "kun_readings": ["こめ", "よね"],
    "on_readings": ["ベイ", "マイ", "メエトル"],
    "name_readings": ["は", "べ", "まべ", "め", "よ", "よな", "よの", "よま"],
    "jlpt": 2,
    "unicode": "7c73",
    "heisig_en": "rice"
  },
  {
    "kanji": "歩",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["walk", "counter for steps"],
    "kun_readings": ["ある.く", "あゆ.む"],
    "on_readings": ["ホ", "ブ", "フ"],
    "name_readings": ["あ", "ゆき", "ゆみ"],
    "jlpt": 3,
    "unicode": "6b69",
    "heisig_en": "walk"
  },
  {
    "kanji": "母",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["mother"],
    "kun_readings": ["はは", "も"],
    "on_readings": ["ボ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "6bcd",
    "heisig_en": "mama"
  },
  {
    "kanji": "方",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["direction", "person", "alternative"],
    "kun_readings": ["かた", "-かた", "-がた"],
    "on_readings": ["ホウ"],
    "name_readings": ["から", "な", "なた", "ふさ", "まさ", "みち", "も", "わ"],
    "jlpt": 3,
    "unicode": "65b9",
    "heisig_en": "direction"
  },
  {
    "kanji": "北",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["north"],
    "kun_readings": ["きた"],
    "on_readings": ["ホク"],
    "name_readings": ["きら", "ほう", "ほっ", "ほつ"],
    "jlpt": 4,
    "unicode": "5317",
    "heisig_en": "north"
  },
  {
    "kanji": "妹",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["younger sister"],
    "kun_readings": ["いもうと"],
    "on_readings": ["マイ"],
    "name_readings": ["す", "せ", "も"],
    "jlpt": 3,
    "unicode": "59b9",
    "heisig_en": "younger sister"
  },
  {
    "kanji": "毎",
    "grade": 2,
    "stroke_count": 6,
    "meanings": ["every"],
    "kun_readings": ["ごと", "-ごと.に"],
    "on_readings": ["マイ"],
    "name_readings": ["つね"],
    "jlpt": 4,
    "unicode": "6bce",
    "heisig_en": "every"
  },
  {
    "kanji": "万",
    "grade": 2,
    "stroke_count": 3,
    "meanings": ["ten thousand", "10,000"],
    "kun_readings": ["よろず"],
    "on_readings": ["マン", "バン"],
    "name_readings": ["かず", "ま", "ゆる"],
    "jlpt": 4,
    "unicode": "4e07",
    "heisig_en": "ten thousand"
  },
  {
    "kanji": "明",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["bright", "light"],
    "kun_readings": [
      "あ.かり",
      "あか.るい",
      "あか.るむ",
      "あか.らむ",
      "あき.らか",
      "あ.ける",
      "-あ.け",
      "あ.く",
      "あ.くる",
      "あ.かす"
    ],
    "on_readings": ["メイ", "ミョウ", "ミン"],
    "name_readings": [
      "あきら",
      "あけ",
      "あす",
      "きら",
      "け",
      "さや",
      "さやか",
      "とし",
      "はる",
      "み",
      "め"
    ],
    "jlpt": 3,
    "unicode": "660e",
    "heisig_en": "bright"
  },
  {
    "kanji": "鳴",
    "grade": 2,
    "stroke_count": 14,
    "meanings": ["chirp", "cry", "bark", "sound", "ring", "echo", "honk"],
    "kun_readings": ["な.く", "な.る", "な.らす"],
    "on_readings": ["メイ"],
    "name_readings": ["なり", "なる"],
    "jlpt": 2,
    "unicode": "9cf4",
    "heisig_en": "chirp"
  },
  {
    "kanji": "毛",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["fur", "hair", "feather", "down"],
    "kun_readings": ["け"],
    "on_readings": ["モウ"],
    "name_readings": ["めん", "も"],
    "jlpt": 2,
    "unicode": "6bdb",
    "heisig_en": "fur"
  },
  {
    "kanji": "門",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["gate", "counter for cannons"],
    "kun_readings": ["かど", "と"],
    "on_readings": ["モン"],
    "name_readings": ["じょう", "も", "と", "ゆき"],
    "jlpt": 3,
    "unicode": "9580",
    "heisig_en": "gates"
  },
  {
    "kanji": "夜",
    "grade": 2,
    "stroke_count": 8,
    "meanings": ["night", "evening"],
    "kun_readings": ["よ", "よる"],
    "on_readings": ["ヤ"],
    "name_readings": [],
    "jlpt": 3,
    "unicode": "591c",
    "heisig_en": "night"
  },
  {
    "kanji": "野",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["plains", "field", "rustic", "civilian life"],
    "kun_readings": ["の", "の-"],
    "on_readings": ["ヤ", "ショ"],
    "name_readings": ["ずけ", "つけ", "ぬ"],
    "jlpt": 3,
    "unicode": "91ce",
    "heisig_en": "plains"
  },
  {
    "kanji": "矢",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["dart", "arrow"],
    "kun_readings": ["や"],
    "on_readings": ["シ"],
    "name_readings": [],
    "jlpt": 1,
    "unicode": "77e2",
    "heisig_en": "dart"
  },
  {
    "kanji": "友",
    "grade": 2,
    "stroke_count": 4,
    "meanings": ["friend"],
    "kun_readings": ["とも"],
    "on_readings": ["ユウ"],
    "name_readings": ["う", "ど", "ゆ"],
    "jlpt": 4,
    "unicode": "53cb",
    "heisig_en": "friend"
  },
  {
    "kanji": "曜",
    "grade": 2,
    "stroke_count": 18,
    "meanings": ["weekday"],
    "kun_readings": [],
    "on_readings": ["ヨウ"],
    "name_readings": ["てる"],
    "jlpt": 3,
    "unicode": "66dc",
    "heisig_en": "weekday"
  },
  {
    "kanji": "用",
    "grade": 2,
    "stroke_count": 5,
    "meanings": ["utilize", "business", "service", "use", "employ"],
    "kun_readings": ["もち.いる"],
    "on_readings": ["ヨウ"],
    "name_readings": ["たから"],
    "jlpt": 3,
    "unicode": "7528",
    "heisig_en": "utilize"
  },
  {
    "kanji": "来",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["come", "due", "next", "cause", "become"],
    "kun_readings": ["く.る", "きた.る", "きた.す", "き.たす", "き.たる", "き", "こ"],
    "on_readings": ["ライ", "タイ"],
    "name_readings": ["くり", "くる", "ごろ", "さ"],
    "jlpt": 4,
    "unicode": "6765",
    "heisig_en": "come"
  },
  {
    "kanji": "理",
    "grade": 2,
    "stroke_count": 11,
    "meanings": ["logic", "arrangement", "reason", "justice", "truth"],
    "kun_readings": ["ことわり"],
    "on_readings": ["リ"],
    "name_readings": [
      "あや",
      "おさむ",
      "さと",
      "さとる",
      "ただ",
      "ただし",
      "とおる",
      "に",
      "のり",
      "ひ",
      "まこと",
      "まさ",
      "まさし",
      "まろ",
      "みち",
      "よし"
    ],
    "jlpt": 3,
    "unicode": "7406",
    "heisig_en": "logic"
  },
  {
    "kanji": "里",
    "grade": 2,
    "stroke_count": 7,
    "meanings": ["ri", "village", "parent's home", "league"],
    "kun_readings": ["さと"],
    "on_readings": ["リ"],
    "name_readings": ["さ"],
    "jlpt": 1,
    "unicode": "91cc",
    "heisig_en": "ri"
  },
  {
    "kanji": "話",
    "grade": 2,
    "stroke_count": 13,
    "meanings": ["tale", "talk"],
    "kun_readings": ["はな.す", "はなし"],
    "on_readings": ["ワ"],
    "name_readings": [],
    "jlpt": 4,
    "unicode": "8a71",
    "heisig_en": "tale"
  }
];
